<a href="https://colab.research.google.com/github/Sharddha-Sharddha/IITMLAssignments/blob/main/AMAZON_fine_food_review_RNN%7CLSTM_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **#Amazon Fine Food Reviews**
Analyze ~500,000 food reviews from Amazon

In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import kagglehub
import os

os is used to connect directly with the dataset by taking the cache

In [8]:
path = kagglehub.dataset_download("snap/amazon-fine-food-reviews")
csv_file = os.path.join(path,'Reviews.csv')
df = pd.read_csv(csv_file)

Using Colab cache for faster access to the 'amazon-fine-food-reviews' dataset.

In [10]:
df.head(2)

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text
0,1,B001E4KFG0,A3SGXH7AUHU8GW,delmartian,1,1,5,1303862400,Good Quality Dog Food,I have bought several of the Vitality canned d...
1,2,B00813GRG4,A1D87F6ZCVE5NK,dll pa,0,0,1,1346976000,Not as Advertised,Product arrived labeled as Jumbo Salted Peanut...

In [11]:
df.shape

(568454, 10)

In [12]:
df.isnull().sum()

Id                         0
ProductId                  0
UserId                     0
ProfileName               26
HelpfulnessNumerator       0
HelpfulnessDenominator     0
Score                      0
Time                       0
Summary                   27
Text                       0
dtype: int64

we only need user's text and score

In [30]:
df_clean = df[['Score','Text']]

In [31]:
df_clean

        Score                                               Text
0           5  I have bought several of the Vitality canned d...
1           1  Product arrived labeled as Jumbo Salted Peanut...
2           4  This is a confection that has been around a fe...
3           2  If you are looking for the secret ingredient i...
4           5  Great taffy at a great price.  There was a wid...
...       ...                                                ...
568449      5  Great for sesame chicken..this is a good if no...
568450      2  I'm disappointed with the flavor. The chocolat...
568451      5  These stars are small, so you can give 10-15 o...
568452      5  These are the BEST treats for training and rew...
568453      5  I am very satisfied ,product is as advertised,...

[568454 rows x 2 columns]

In [32]:
df_clean.isnull().sum()

Score    0
Text     0
dtype: int64

In [41]:
df_clean['Text'][2]

'This is a confection that has been around a few centuries.  It is a light, pillowy citrus gelatin with nuts - in this case Filberts. And it is cut into tiny squares and then liberally coated with powdered sugar.  And it is a tiny mouthful of heaven.  Not too chewy, and very flavorful.  I highly recommend this yummy treat.  If you are familiar with the story of C.S. Lewis\' "The Lion, The Witch, and The Wardrobe" - this is the treat that seduces Edmund into selling out his Brother and Sisters to the Witch.'

In [42]:
df_clean['Score'][2]

np.int64(4)

In [40]:
#rating distribution
score_counts = df_clean['Score'].value_counts().sort_index()
print('\nPercentage')
for score, count in score_counts.items():
  perc = (count/len(df_clean)) * 100
  print(f"{score} 🌟 : {perc:.2f}%")

Percentage
1 🌟 : 9.19%
2 🌟 : 5.24%
3 🌟 : 7.50%
4 🌟 : 14.19%
5 🌟 : 63.88%

we can clearly see there is a data emblance

Q: which product is given more preference and which product gives leass preference

In [73]:
product_stat= df.groupby('ProductId')['Score'].agg(['mean', 'count'])

most_preferred= product_stat[product_stat['count']>50].sort_values(by='mean', ascending=False)
most_preferred.head(2)

                mean  count
ProductId
B000ED9L9E  4.973451    113
B000O5DI1E  4.906542    107